export const FILTER = {
	OPTIONS: {
		ADD: 'ADD_OPTION',
		DELETE: 'DELETE_OPTION',
		CLEAR: 'CLEAR_OPTIONS'
	},
	COMPANIES: {
		ADD: 'ADD_COMPANY',
		DELETE: 'DELETE_COMPANY',
		CLEAR: 'CLEAR_COMPANIES'
	},
};

export const AIRLINES = {
	SET: 'SET_AIRLINES'
};