export const FILTER = {
	OPTIONS: {
		ADD: 'ADD_OPTION',
		DELETE: 'DELETE_OPTION'
	},
	COMPANIES: {
		ADD: 'ADD_COMPANY',
		DELETE: 'DELETE_COMPANY'
	},
};

export const AIRLINES = {
	SET: 'SET_AIRLINES'
};